### ISSUE TITLE
Offer downloadable datasets at osm.be

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/projects#1]

**Comment by jbelien** [comment]
Definitely a good idea ! 👍 
Especially since Mapzen is out : they provided extracts for Brussels and Antwerpen (where Geofabriek only provides country extracts).

Need to answer some questions though :
- Why ? (use-cases ? advantage compared to Geofabriek ?)
- How ?
- What update rate ?
- ...

Geofabriek extract details : http://download.geofabrik.de/technical.html
Mapzen extract details : https://github.com/mapzen/chef-metroextractor

**Comment by xivk** [comment]
I think we need to collect use-cases on demand. I'm thinking about data we only map or we have better data for.

Why not create an extract for all cycle networks in Brussels in geojson for example?

**Comment by jbelien** [comment]
Oh yes, dedicated extract, that's a good idea :)

**Comment by joostschouppe** [comment]
Well a clearly defined use case is "a routable dataset of Belgium", and I believe it's already available on someone's server ;)

**Comment by jbelien** [comment]
Moved to https://github.com/osmbe/community_planning/issues/7
